### ISSUE TITLE
Next.js server stuck on compiling

### ISSUE THREAD

**Issue by Sama-004** [manakuro/project-management-demo-frontend#55]
# Description of the issue

stuck at waiting for compiling 

wait  - compiling /[[...index]] (client and server)...

I have the added the environment variables

# Steps to reproduce

Clone the repository.
Run `yarn install` to install dependencies.
Run `yarn dev` to start the development server.
The server starts successfully but gets stuck on compiling the page /[[...index]] without completing.

# Whole output

```
~/❯ yarn dev
(node:139539) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
ready - started server on 0.0.0.0:4001, url: http://localhost:4001
info  - Loaded env from /home/sama/projects/asana/frontend/.env.local
info  - Loaded env from /home/sama/projects/asana/frontend/.env
warn  - You have enabled experimental feature (esmExternals) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

event - compiled client and server successfully in 3.9s (5851 modules)
wait  - compiling /[[...index]] (client and server)...
event - compiled client and server successfully in 661 ms (6236 modules)
```

**Comment by manakuro** [comment]
In order to start the server, the backend server needs to be started. 

Try to follow the steps.

1. Set up the backend server by following [the steps](https://github.com/manakuro/project-management-demo-backend).
2. Start the backend server
3. Go to the frontend repository, run the command `yarn codegen` which will generate a TypeScript types of GraphQL scheme.
4. Set up [Firebase project](https://firebase.google.com/)
5. In the frontend repository, create a `.env.local` in the root. And apply the firebase information like this.

```.evn.local
NEXT_PUBLIC_APP_ENV=development
NEXT_PUBLIC_API_URL=http://localhost:8082/api/graphql
NEXT_PUBLIC_API_SUBSCRIPTION_URL=ws://localhost:8082/api/subscription
NEXT_PUBLIC_FIREBASE_API_KEY="your FIREBASE_API_KEY"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="your FIREBASE_AUTH_DOMAIN"
NEXT_PUBLIC_FIREBASE_PROJECT_ID="your FIREBASE_PROJECT_ID"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="your FIREBASE_STORAGE_BUCKET"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="your FIREBASE_MESSAGING_SENDER_ID"
NEXT_PUBLIC_FIREBASE_APPID="your FIREBASE_APPID"
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="your FIREBASE_MEASUREMENT_ID"
```

Then, run the command, `yarn dev` to start the server.

**Comment by Sama-004** [comment]
> In order to start the server, the backend server needs to be started.
> 
> Try to follow the steps.
> 
>     1. Set up the backend server by following [the steps](https://github.com/manakuro/project-management-demo-backend).
> 
>     2. Start the backend server
> 
>     3. Go to the frontend repository, run the command `yarn codegen` which will generate a TypeScript types of GraphQL scheme.
> 
>     4. Set up [Firebase project](https://firebase.google.com/)
> 
>     5. In the frontend repository, create a `.env.local` in the root. And apply the firebase information like this.
> 
> 
> ```
> NEXT_PUBLIC_APP_ENV=development
> NEXT_PUBLIC_API_URL=http://localhost:8082/api/graphql
> NEXT_PUBLIC_API_SUBSCRIPTION_URL=ws://localhost:8082/api/subscription
> NEXT_PUBLIC_FIREBASE_API_KEY="your FIREBASE_API_KEY"
> NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="your FIREBASE_AUTH_DOMAIN"
> NEXT_PUBLIC_FIREBASE_PROJECT_ID="your FIREBASE_PROJECT_ID"
> NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="your FIREBASE_STORAGE_BUCKET"
> NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="your FIREBASE_MESSAGING_SENDER_ID"
> NEXT_PUBLIC_FIREBASE_APPID="your FIREBASE_APPID"
> NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="your FIREBASE_MEASUREMENT_ID"
> ```
> 
> Then, run the command, `yarn dev` to start the server.



I was almost correct with the env vars just got the endpoint of the api wrong.

And after that I was getting this error message saying invalid login credentials. So i added a console.error in the `download.js` file and then it said 

```
Error in download.js Error: No introspection query result data found, server responded with: {"type":"/api/graphql","title":"cannot read credentials file: open .keys/firebase-service-key.json: no such file or directory","status":401}
```

So i created a node.js service key and added it to `.keys` directoy but after that now I am getting this error. Do you have any idea on how this can be fixed? or what's wrong here   


```
~ ❯ yarn codegen                                                                                                                                         
Token: {
  error: {
    code: 400,
    message: 'INVALID_LOGIN_CREDENTIALS',
    errors: [ [Object] ]
  }
}
ℹ Access Token:  undefined                                                                                                                                                           
(node:44100) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error in download.js Error: No introspection query result data found, server responded with: {"type":"/api/graphql","title":"incorrect number of segments; see https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve a valid ID token","status":401}
    at downloadSchema (/home/sama/projects/asana/frontend/scripts/codegen/downloadSchema.js:44:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async download (/home/sama/projects/asana/frontend/scripts/codegen/download.js:15:5)

 WARN  Auth response is status code: 401                                                                                                                                              
```

**Comment by manakuro** [comment]
I missed the step of that. The `.keys` should be the Service Account Key of Firebase.

Create the key in the backend repository and try again?

1. Go to your Firebase Console and create service account key.
   - See the step: https://firebase.google.com/docs/admin/setup#initialize_the_sdk_in_non-google_environments
2. Copy the JSON file that you've created
3. In the backend repository, create the `.keys/firebase-service-key.json` and paste the above JSON file like this.

```json
{
  "type": "service_account",
  "project_id": "...",
  "private_key_id": "...",
  "private_key": "-----BEGIN PRIVATE KEY-----E=\n-----END PRIVATE KEY-----\n",
  "client_email": "...",
  "client_id": "...",
  "auth_uri": "...",
  "token_uri": "...",
  "auth_provider_x509_cert_url": "...",
  "client_x509_cert_url": "..."
}
```

Then start the backend server and try running the `yarn dev` again?

**Comment by Sama-004** [comment]
It works now thanks for the help
